spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.824a9f32097a1d07
            client-secret: c28b2430e1575d546a668e43d62ac1400569cd0c
  data:
    cassandra:
      keyspace-name: main
      username: IWUvtJrbKCoIGsKCvTOXloOz
      password: lUCmag54N4NPHX-20Gn_,rssK0fIZjZ-X+pFC-.UOhvEs+ASlSL3.SsYvdivZQJWciT4SPf9MG3xoqyYwvnpEvYzyixNwCy+ZZrCfSz0tvZEUxoCZa7bv7D37Y9.8ZxK
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra:
  db:
    id: 2abf87bf-99ee-482a-92b8-41c53afdaaf4-1
    region: us-east1
    keyspace: main
    application:
      token: AstraCS:IWUvtJrbKCoIGsKCvTOXloOz:1e26597809ee03a9615e5aea5db0b0af788a255c9890d8ccc9c11b472c6cfacb

datastax.astra:
  secure-connect-bundle: secure-connect.zip
