spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.824a9f32097a1d07
            client-secret: c28b2430e1575d546a668e43d62ac1400569cd0c
  data:
    cassandra:
      keyspace-name: main
      username: IBFNpbnGnFTiUBPJaiMLqUzG
      password: bjLlDqi4JlyORjBvRO2P+4Ciyrk_hE3ltTMA-.DzTR2nYcX608KAQld21bD5SOo0fEJc1_l+nZrZzSoxIfpbbSA8yFDHBc9moRto6AOeMmHq3DTZi7.gJ9H0w3n4rXDI
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
#  main:
#    allow-circular-references: true
#
astra:
  db:
    id: 2bbb1d01-4a33-4b65-ba10-235bbe575d0b-1
    region: us-east1
    keyspace: main
    application:
      token: AstraCS:IBFNpbnGnFTiUBPJaiMLqUzG:6d578f87ecfa0cf12c3c46a10b19a20fd64ad02c4afd0297a180386679250afd

datastax.astra:
  secure-connect-bundle: secure-connect-inbox-app.zip

